version: '3.4'

services:
  phoenixd:
    build:
      context: ./phoenixd
      dockerfile: Dockerfile
    ports:
      - "9740:9740"
    networks:
      - my_network

  lnbits:
    build:
      context: ./lnbits
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my_network

networks:
  my_network:
